export const GET_CATEGORY = "http://localhost:3000/category";
export const GET_ITEM = "http://localhost:3000/item";
export const GET_IMAGES = "http://localhost:3000/images";
export const GET_ITEM_ID = "http://localhost:3000/item/:id";
export const POST_USER_REGISTER = "http://localhost:3000/user/";
export const POST_USER_LOGIN = "http://localhost:3000/login";
export const NOTIFICATIONURL = "http://localhost:3000/subscribe";
export const DASHBOARD_URL="http://localhost:3000/statisque";
export const VALID_KEY = "BIrUKIPVB5BW7uxFCF8wihQOMhGzCZBxvDcb8JkzEyN3EhDOeemMwBXfc64MEHCzCz9QgQV4C1EAfKkuxwy0h2w";